#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
KIMI_SWING_PRO - NSE SECTOR & SWING TRADE SCANNER (GOD MODE)
================================================================================
Scrapes top delivery data from scanx.trade, maps stocks to sectors,
analyzes 2-week sector performance, and finds the best swing trade setups.

OUTPUT: C:\\Deal\\Kimi_Swing_Pro\\KIMI_SWING_PRO_YYYYMMDD_HHMMSS.xlsx

Author: Generated by Kimi AI
Date: 2026-07-11

INSTALL DEPENDENCIES:
    pip install requests beautifulsoup4 pandas numpy yfinance lxml openpyxl

USAGE:
    python nse_sector_swing_scanner.py
    python nse_sector_swing_scanner.py --sector "IT" --min-score 5
    python nse_sector_swing_scanner.py --top-n 15

FEATURES:
    - Auto-scrapes scanx.trade top deliveries page
    - Maps 50+ NSE stocks to their sectors
    - Calculates 2-week sector momentum ranking
    - Full technical analysis (EMA, RSI, MACD, ATR, Volume, BB, ADX, OBV, Stoch)
    - Swing trade scoring with entry/stop/target
    - Auto-exports to Excel at C:\\Deal\\Kimi_Swing_Pro
    - 6 sheets: Scan_Info, Sector_Analysis, All_Swing_Trades,
      BULLISH_Signals, BEARISH_Signals, TOP_PICKS
================================================================================
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import yfinance as yf
import argparse
import json
import os
import sys
from datetime import datetime, timedelta
from collections import defaultdict
import warnings
warnings.filterwarnings('ignore')

# =============================================================================
# CONFIGURATION
# =============================================================================

SCANX_URL = "https://scanx.trade/insight/top-deliveries"

# Stock-to-Sector mapping for NSE stocks
STOCK_SECTOR_MAP = {
    # IT / Technology
    "TCS": "IT", "INFY": "IT", "WIPRO": "IT", "HCLTECH": "IT",
    "TECHM": "IT", "LTIM": "IT", "PERSISTENT": "IT", "MPHASIS": "IT",
    "COFORGE": "IT", "ZOMATO": "IT", "PAYTM": "IT", "POLICYBZR": "IT",

    # Banking / Financials
    "HDFCBANK": "BANKING", "ICICIBANK": "BANKING", "KOTAKBANK": "BANKING",
    "AXISBANK": "BANKING", "SBIN": "BANKING", "INDUSINDBK": "BANKING",
    "BANDHANBNK": "BANKING", "FEDERALBNK": "BANKING", "IDFCFIRSTB": "BANKING",
    "BAJFINANCE": "FINANCIALS", "BAJAJFINSV": "FINANCIALS", "SHRIRAMFIN": "FINANCIALS",
    "CHOLAFIN": "FINANCIALS", "MUTHOOTFIN": "FINANCIALS", "POONAWALLA": "FINANCIALS",
    "HDFCLIFE": "FINANCIALS", "SBILIFE": "FINANCIALS", "ICICIPRULI": "FINANCIALS",
    "JIOFIN": "FINANCIALS",

    # Auto
    "MARUTI": "AUTO", "TATAMOTORS": "AUTO", "M&M": "AUTO", "BAJAJ-AUTO": "AUTO",
    "HEROMOTOCO": "AUTO", "EICHERMOT": "AUTO", "ASHOKLEY": "AUTO", "TVSMOTOR": "AUTO",
    "MOTHERSON": "AUTO", "BHARATFORG": "AUTO",

    # FMCG / Consumer
    "HINDUNILVR": "FMCG", "ITC": "FMCG", "NESTLEIND": "FMCG", "BRITANNIA": "FMCG",
    "TATACONSUM": "FMCG", "DABUR": "FMCG", "GODREJCP": "FMCG", "MARICO": "FMCG",
    "COLPAL": "FMCG", "PGHH": "FMCG", "VBL": "FMCG", "UNITDSPR": "FMCG",
    "TRENT": "FMCG", "ZOMATO": "FMCG",

    # Pharma / Healthcare
    "SUNPHARMA": "PHARMA", "DRREDDY": "PHARMA", "CIPLA": "PHARMA", "DIVISLAB": "PHARMA",
    "BIOCON": "PHARMA", "AUROPHARMA": "PHARMA", "LUPIN": "PHARMA", "TORNTPHARM": "PHARMA",
    "APOLLOHOSP": "PHARMA", "MAXHEALTH": "PHARMA", "FORTIS": "PHARMA",

    # Oil & Gas / Energy
    "RELIANCE": "OIL_GAS", "ONGC": "OIL_GAS", "IOC": "OIL_GAS", "BPCL": "OIL_GAS",
    "HINDPETRO": "OIL_GAS", "GAIL": "OIL_GAS", "PETRONET": "OIL_GAS",
    "NTPC": "POWER", "POWERGRID": "POWER", "ADANIPOWER": "POWER", "TATAPOWER": "POWER",
    "JSWENERGY": "POWER", "NHPC": "POWER",
    "COALINDIA": "METALS_MINING",

    # Metals & Mining
    "TATASTEEL": "METALS_MINING", "JSWSTEEL": "METALS_MINING", "HINDALCO": "METALS_MINING",
    "VEDL": "METALS_MINING", "NMDC": "METALS_MINING", "JINDALSTEL": "METALS_MINING",
    "SAIL": "METALS_MINING", "NATIONALUM": "METALS_MINING",

    # Cement / Infrastructure
    "ULTRACEMCO": "CEMENT", "SHREECEM": "CEMENT", "GRASIM": "CEMENT",
    "AMBUJACEM": "CEMENT", "ACC": "CEMENT", "RAMCOCEM": "CEMENT", "DALBHARAT": "CEMENT",
    "LT": "INFRA", "DLF": "INFRA", "OBEROIRLTY": "INFRA", "PHOENIXLTD": "INFRA",
    "GODREJPROP": "INFRA", "BRIGADE": "INFRA", "PRESTIGE": "INFRA",

    # Telecom
    "BHARTIARTL": "TELECOM", "IDEA": "TELECOM",

    # Chemicals
    "UPL": "CHEMICALS", "PIIND": "CHEMICALS", "SRF": "CHEMICALS",
    "ATUL": "CHEMICALS", "DEEPAKNTR": "CHEMICALS", "NAVINFLUOR": "CHEMICALS",
    "GUJFLUORO": "CHEMICALS", "ALKYLAMINE": "CHEMICALS",

    # Capital Goods / Engineering
    "SIEMENS": "CAPITAL_GOODS", "ABB": "CAPITAL_GOODS", "HAL": "CAPITAL_GOODS",
    "BEL": "CAPITAL_GOODS", "BHEL": "CAPITAL_GOODS", "CGPOWER": "CAPITAL_GOODS",
    "THERMAX": "CAPITAL_GOODS", "CUMMINSIND": "CAPITAL_GOODS",

    # Others
    "TITAN": "RETAIL", "ASIANPAINT": "RETAIL", "BERGEPAINT": "RETAIL",
    "KANSAINER": "RETAIL", "INDIGO": "AVIATION", "INTERGLOBE": "AVIATION",
    "ADANIPORTS": "LOGISTICS", "ADANIENT": "CONGLOMERATE",
}

SECTOR_NAMES = {
    "IT": "Information Technology",
    "BANKING": "Banking",
    "FINANCIALS": "Financial Services",
    "AUTO": "Automobile",
    "FMCG": "FMCG / Consumer",
    "PHARMA": "Pharma / Healthcare",
    "OIL_GAS": "Oil & Gas",
    "POWER": "Power / Energy",
    "METALS_MINING": "Metals & Mining",
    "CEMENT": "Cement",
    "INFRA": "Infrastructure / Real Estate",
    "TELECOM": "Telecom",
    "CHEMICALS": "Chemicals",
    "CAPITAL_GOODS": "Capital Goods",
    "RETAIL": "Retail / Consumer Durables",
    "AVIATION": "Aviation",
    "LOGISTICS": "Logistics",
    "CONGLOMERATE": "Conglomerate",
}


# =============================================================================
# SCANX SCRAPER
# =============================================================================

class ScanXScraper:
    """Scrapes top delivery data from scanx.trade"""

    def __init__(self, url=SCANX_URL):
        self.url = url
        self.used_fallback = False
        self.headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
        }

    def fetch(self):
        """Fetch and parse the scanx top deliveries page."""
        print(f"[SCANX] Fetching data from {self.url}...")
        try:
            response = requests.get(self.url, headers=self.headers, timeout=30)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, 'lxml')
            return self._parse_table(soup)
        except Exception as e:
            print(f"[ERROR] Failed to fetch scanx data: {e}")
            self.used_fallback = True
            return self._fallback_data()

    def _parse_table(self, soup):
        """Parse the HTML table from scanx page."""
        stocks = []

        # Find all table rows or card elements
        # The page uses a card-based layout with stock info
        rows = soup.find_all('tr')

        for row in rows:
            cells = row.find_all(['td', 'th'])
            if len(cells) >= 7:
                try:
                    # Extract text from cells
                    texts = [cell.get_text(strip=True) for cell in cells]

                    # Try to identify stock name (first meaningful cell)
                    name = texts[0].strip()
                    if not name or len(name) < 2:
                        continue

                    # Parse numeric values
                    def parse_num(s):
                        s = s.replace(',', '').replace('%', '').strip()
                        try:
                            return float(s)
                        except:
                            return 0.0

                    # Map columns: Name, LTP, Change, Change%, Volume, Delivery, Deliv%
                    stock = {
                        'name': name,
                        'ltp': parse_num(texts[1]) if len(texts) > 1 else 0,
                        'change': parse_num(texts[2]) if len(texts) > 2 else 0,
                        'change_pct': parse_num(texts[3]) if len(texts) > 3 else 0,
                        'volume': parse_num(texts[4]) if len(texts) > 4 else 0,
                        'delivery_qty': parse_num(texts[5]) if len(texts) > 5 else 0,
                        'delivery_pct': parse_num(texts[6]) if len(texts) > 6 else 0,
                    }

                    # Clean name - extract ticker
                    stock['ticker'] = self._extract_ticker(name)
                    stock['sector'] = STOCK_SECTOR_MAP.get(stock['ticker'], "UNKNOWN")

                    if stock['ltp'] > 0:
                        stocks.append(stock)

                except Exception as e:
                    continue

        if not stocks:
            # Try alternative parsing - look for div/card structures
            cards = soup.find_all('div', class_=lambda x: x and 'stock' in str(x).lower())
            for card in cards:
                # Fallback parsing logic
                pass

        if not stocks:
            self.used_fallback = True
            return self._fallback_data()

        print(f"[SCANX] Parsed {len(stocks)} stocks from scanx.trade")
        return pd.DataFrame(stocks)

    def _extract_ticker(self, name):
        """Extract NSE ticker from company name."""
        name_upper = name.upper().replace(' ', '').replace('.', '').replace('&', '')

        # Direct mappings for common names
        name_map = {
            'ASIANPAINTS': 'ASIANPAINT',
            'HINDUSTANUNILEVER': 'HINDUNILVR',
            'HINDUSTANUNILEVERLIMITED': 'HINDUNILVR',
            'STATEBANKOFINDIA': 'SBIN',
            'LARSENANDTOUBRO': 'LT',
            'LARSENTOUBRO': 'LT',
            'TATAMOTORSPASSENGERVEHICLES': 'TATAMOTORS',
            'INTERGLOBEAVIATION': 'INDIGO',
            'OILANDNATURALGASCORPORATION': 'ONGC',
            'POWERGRIDCORPORATIONOFINDIA': 'POWERGRID',
            'MAXHEALTHCAREINSTITUTE': 'MAXHEALTH',
            'TATACONSULTANCYSERVICES': 'TCS',
            'JIOFINANCIALSERVICES': 'JIOFIN',
            'ADANIPORTSANDSEZ': 'ADANIPORTS',
            'DRREDDYS': 'DRREDDY',
            'DRREDDYSLABORATORIES': 'DRREDDY',
            'SUNPHARMACEUTICAL': 'SUNPHARMA',
            'APOLLOHOSPITALSENTERPRISE': 'APOLLOHOSP',
            'HCLTECHNOLOGIES': 'HCLTECH',
            'MAHINDRAANDMAHINDRA': 'MM',
            'MAHINDRAMAHINDRA': 'MM',
            'BHARATELECTRONICS': 'BEL',
            'NESTLEINDIA': 'NESTLEIND',
            'ULTRATECHCEMENT': 'ULTRACEMCO',
            'TATACONSUMERPRODUCTS': 'TATACONSUM',
            'SHRIRAMFINANCE': 'SHRIRAMFIN',
            'HDFCLIFEINSURANCE': 'HDFCLIFE',
            'SBILIFEINSURANCE': 'SBILIFE',
            'ADANIENTERPRISES': 'ADANIENT',
            'ADANIPORTSANDSEZ': 'ADANIPORTS',
            'GRASIMINDUSTRIES': 'GRASIM',
            'JSWSTEEL': 'JSWSTEEL',
            'HINDALCOINDUSTRIES': 'HINDALCO',
            'TATASTEEL': 'TATASTEEL',
            'BHARATFORGE': 'BHARATFORG',
            'TECHMAHINDRA': 'TECHM',
            'HINDUSTANPETROLEUM': 'HINDPETRO',
            'INDIANOILCORPORATION': 'IOC',
            'BHARATPETROLEUM': 'BPCL',
            'COALINDIA': 'COALINDIA',
            'NMDC': 'NMDC',
            'NATIONALALUMINIUM': 'NATIONALUM',
            'JINDALSTEEL': 'JINDALSTEL',
            'SAIL': 'SAIL',
            'AMBUJACEMENTS': 'AMBUJACEM',
            'ACC': 'ACC',
            'SHREECEMENT': 'SHREECEM',
            'DALMIABHARAT': 'DALBHARAT',
            'RAMCOCEMENTS': 'RAMCOCEM',
            'DLF': 'DLF',
            'OBEROIREALTY': 'OBEROIRLTY',
            'PHOENIXMILLS': 'PHOENIXLTD',
            'GODREJPROPERTIES': 'GODREJPROP',
            'BRIGADEENTERPRISES': 'BRIGADE',
            'PRESTIGEESTATES': 'PRESTIGE',
            'VODAFONEIDEA': 'IDEA',
            'UPL': 'UPL',
            'PIINDUSTRIES': 'PIIND',
            'SRF': 'SRF',
            'ATUL': 'ATUL',
            'DEEPAKNITRITE': 'DEEPAKNTR',
            'NAVINFLUORINE': 'NAVINFLUOR',
            'GUJARATFLUOROCHEMICALS': 'GUJFLUORO',
            'ALKYLAMINES': 'ALKYLAMINE',
            'SIEMENS': 'SIEMENS',
            'ABBINDIA': 'ABB',
            'HINDUSTANAERONAUTICS': 'HAL',
            'BHARATELECTRONICS': 'BEL',
            'BHARATHEAVYELECTRICALS': 'BHEL',
            'CGPOWERANDINDUSTRIALSOLUTIONS': 'CGPOWER',
            'THERMAX': 'THERMAX',
            'CUMMINSINDIA': 'CUMMINSIND',
            'TITANCOMPANY': 'TITAN',
            'ASIANPAINTS': 'ASIANPAINT',
            'BERGERPAINTS': 'BERGEPAINT',
            'KANSAINEROLAC': 'KANSAINER',
            'INDIGO': 'INDIGO',
            'ADANIPORTS': 'ADANIPORTS',
            'ADANIENTERPRISES': 'ADANIENT',
            'ETERNAL': 'ETERNAL',
        }

        for key, val in name_map.items():
            if key in name_upper:
                return val

        # Try to find exact match in map keys
        for ticker in STOCK_SECTOR_MAP.keys():
            if ticker in name_upper:
                return ticker

        return name_upper[:20]  # Return truncated name as fallback

    def _fallback_data(self):
        """Fallback data if scraping fails."""
        print("[FALLBACK] Using cached scanx-style data...")
        fallback = [
            {"name": "Asian Paints", "ticker": "ASIANPAINT", "ltp": 2635.70, "change": -21.20, "change_pct": -0.80, "volume": 4752587, "delivery_qty": 3790723, "delivery_pct": 79.76, "sector": "RETAIL"},
            {"name": "NTPC", "ticker": "NTPC", "ltp": 356.65, "change": 0.55, "change_pct": 0.15, "volume": 49895302, "delivery_qty": 38451958, "delivery_pct": 77.07, "sector": "POWER"},
            {"name": "ICICI Bank", "ticker": "ICICIBANK", "ltp": 1375.20, "change": -12.40, "change_pct": -0.89, "volume": 13249405, "delivery_qty": 10075322, "delivery_pct": 76.04, "sector": "BANKING"},
            {"name": "Interglobe Aviation", "ticker": "INDIGO", "ltp": 5368.40, "change": 53.20, "change_pct": 1.00, "volume": 2860034, "delivery_qty": 2120043, "delivery_pct": 74.13, "sector": "AVIATION"},
            {"name": "Maruti Suzuki", "ticker": "MARUTI", "ltp": 14115.00, "change": 703.00, "change_pct": 5.24, "volume": 1358592, "delivery_qty": 1003504, "delivery_pct": 73.86, "sector": "AUTO"},
            {"name": "SBI Life Insurance", "ticker": "SBILIFE", "ltp": 1765.70, "change": 10.30, "change_pct": 0.59, "volume": 3910884, "delivery_qty": 2887976, "delivery_pct": 73.84, "sector": "FINANCIALS"},
            {"name": "Tata Steel", "ticker": "TATASTEEL", "ltp": 188.06, "change": -1.51, "change_pct": -0.80, "volume": 62549132, "delivery_qty": 46178174, "delivery_pct": 73.83, "sector": "METALS_MINING"},
            {"name": "Eicher Motors", "ticker": "EICHERMOT", "ltp": 7073.50, "change": -352.50, "change_pct": -4.75, "volume": 2326377, "delivery_qty": 1704611, "delivery_pct": 73.27, "sector": "AUTO"},
            {"name": "Bajaj Finance", "ticker": "BAJFINANCE", "ltp": 1004.75, "change": 28.70, "change_pct": 2.94, "volume": 19875760, "delivery_qty": 14500590, "delivery_pct": 72.96, "sector": "FINANCIALS"},
            {"name": "Bajaj Finserv", "ticker": "BAJAJFINSV", "ltp": 1780.20, "change": 22.40, "change_pct": 1.27, "volume": 1565424, "delivery_qty": 1142045, "delivery_pct": 72.95, "sector": "FINANCIALS"},
            {"name": "Hindustan Unilever", "ticker": "HINDUNILVR", "ltp": 2118.20, "change": -33.10, "change_pct": -1.54, "volume": 1423514, "delivery_qty": 1031938, "delivery_pct": 72.49, "sector": "FMCG"},
            {"name": "State Bank of India", "ticker": "SBIN", "ltp": 1026.90, "change": -9.20, "change_pct": -0.89, "volume": 16818246, "delivery_qty": 11810287, "delivery_pct": 70.22, "sector": "BANKING"},
            {"name": "Axis Bank", "ticker": "AXISBANK", "ltp": 1345.70, "change": -11.10, "change_pct": -0.82, "volume": 12602010, "delivery_qty": 8837263, "delivery_pct": 70.13, "sector": "BANKING"},
            {"name": "Coal India", "ticker": "COALINDIA", "ltp": 439.05, "change": -5.80, "change_pct": -1.30, "volume": 21400224, "delivery_qty": 14968027, "delivery_pct": 69.94, "sector": "METALS_MINING"},
            {"name": "Shriram Finance", "ticker": "SHRIRAMFIN", "ltp": 1042.15, "change": 9.50, "change_pct": 0.92, "volume": 11369236, "delivery_qty": 7944743, "delivery_pct": 69.88, "sector": "FINANCIALS"},
            {"name": "Power Grid", "ticker": "POWERGRID", "ltp": 286.30, "change": 0.05, "change_pct": 0.02, "volume": 16957025, "delivery_qty": 11736859, "delivery_pct": 69.22, "sector": "POWER"},
            {"name": "Grasim Industries", "ticker": "GRASIM", "ltp": 3100.00, "change": 19.80, "change_pct": 0.64, "volume": 1286143, "delivery_qty": 888259, "delivery_pct": 69.06, "sector": "CEMENT"},
            {"name": "Nestle India", "ticker": "NESTLEIND", "ltp": 1405.20, "change": 17.90, "change_pct": 1.29, "volume": 3412530, "delivery_qty": 2326893, "delivery_pct": 68.19, "sector": "FMCG"},
            {"name": "Bharti Airtel", "ticker": "BHARTIARTL", "ltp": 1852.00, "change": 10.90, "change_pct": 0.59, "volume": 10940130, "delivery_qty": 7456784, "delivery_pct": 68.16, "sector": "TELECOM"},
            {"name": "UltraTech Cement", "ticker": "ULTRACEMCO", "ltp": 11253.00, "change": -83.00, "change_pct": -0.73, "volume": 230886, "delivery_qty": 153738, "delivery_pct": 66.59, "sector": "CEMENT"},
            {"name": "HDFC Bank", "ticker": "HDFCBANK", "ltp": 797.95, "change": -0.95, "change_pct": -0.12, "volume": 46695977, "delivery_qty": 30919361, "delivery_pct": 66.21, "sector": "BANKING"},
            {"name": "Reliance Industries", "ticker": "RELIANCE", "ltp": 1293.90, "change": -7.10, "change_pct": -0.55, "volume": 13757656, "delivery_qty": 8969596, "delivery_pct": 65.20, "sector": "OIL_GAS"},
            {"name": "Titan", "ticker": "TITAN", "ltp": 4404.00, "change": 126.80, "change_pct": 2.96, "volume": 569087, "delivery_qty": 368429, "delivery_pct": 64.74, "sector": "RETAIL"},
            {"name": "Kotak Bank", "ticker": "KOTAKBANK", "ltp": 392.25, "change": -3.25, "change_pct": -0.82, "volume": 37210245, "delivery_qty": 24071034, "delivery_pct": 64.69, "sector": "BANKING"},
            {"name": "Tech Mahindra", "ticker": "TECHM", "ltp": 1404.70, "change": -29.10, "change_pct": -2.03, "volume": 2466821, "delivery_qty": 1592669, "delivery_pct": 64.56, "sector": "IT"},
            {"name": "Wipro", "ticker": "WIPRO", "ltp": 170.39, "change": -5.09, "change_pct": -2.90, "volume": 24484011, "delivery_qty": 15754931, "delivery_pct": 64.35, "sector": "IT"},
            {"name": "Bharat Electronics", "ticker": "BEL", "ltp": 411.80, "change": 0.20, "change_pct": 0.05, "volume": 26669735, "delivery_qty": 16767958, "delivery_pct": 62.87, "sector": "CAPITAL_GOODS"},
            {"name": "Bajaj Auto", "ticker": "BAJAJ-AUTO", "ltp": 9716.00, "change": 86.00, "change_pct": 0.89, "volume": 515976, "delivery_qty": 323097, "delivery_pct": 62.62, "sector": "AUTO"},
            {"name": "Larsen & Toubro", "ticker": "LT", "ltp": 4143.40, "change": -21.80, "change_pct": -0.52, "volume": 2706906, "delivery_qty": 1694574, "delivery_pct": 62.60, "sector": "INFRA"},
            {"name": "JSW Steel", "ticker": "JSWSTEEL", "ltp": 1226.40, "change": -6.00, "change_pct": -0.49, "volume": 2091046, "delivery_qty": 1300719, "delivery_pct": 62.20, "sector": "METALS_MINING"},
            {"name": "Hindalco Industries", "ticker": "HINDALCO", "ltp": 956.60, "change": -7.20, "change_pct": -0.75, "volume": 9499504, "delivery_qty": 5892111, "delivery_pct": 62.03, "sector": "METALS_MINING"},
            {"name": "ONGC", "ticker": "ONGC", "ltp": 234.90, "change": 0.85, "change_pct": 0.36, "volume": 38227413, "delivery_qty": 23475141, "delivery_pct": 61.41, "sector": "OIL_GAS"},
            {"name": "Mahindra & Mahindra", "ticker": "MM", "ltp": 3068.80, "change": -24.20, "change_pct": -0.78, "volume": 3700623, "delivery_qty": 2242725, "delivery_pct": 60.60, "sector": "AUTO"},
            {"name": "ITC", "ticker": "ITC", "ltp": 286.95, "change": -3.75, "change_pct": -1.29, "volume": 10110022, "delivery_qty": 6112475, "delivery_pct": 60.46, "sector": "FMCG"},
            {"name": "HDFC Life", "ticker": "HDFCLIFE", "ltp": 575.85, "change": -7.40, "change_pct": -1.27, "volume": 4808121, "delivery_qty": 2863907, "delivery_pct": 59.56, "sector": "FINANCIALS"},
            {"name": "Infosys", "ticker": "INFY", "ltp": 1000.40, "change": -36.30, "change_pct": -3.50, "volume": 15080892, "delivery_qty": 8909976, "delivery_pct": 59.08, "sector": "IT"},
            {"name": "Apollo Hospitals", "ticker": "APOLLOHOSP", "ltp": 8682.00, "change": 27.00, "change_pct": 0.31, "volume": 363592, "delivery_qty": 210207, "delivery_pct": 57.81, "sector": "PHARMA"},
            {"name": "Sun Pharmaceutical", "ticker": "SUNPHARMA", "ltp": 1862.50, "change": -12.30, "change_pct": -0.66, "volume": 1655869, "delivery_qty": 952081, "delivery_pct": 57.50, "sector": "PHARMA"},
            {"name": "Adani Ports", "ticker": "ADANIPORTS", "ltp": 1810.20, "change": 34.10, "change_pct": 1.92, "volume": 1693498, "delivery_qty": 957690, "delivery_pct": 56.55, "sector": "LOGISTICS"},
            {"name": "Max Healthcare", "ticker": "MAXHEALTH", "ltp": 1129.25, "change": -20.65, "change_pct": -1.80, "volume": 4106274, "delivery_qty": 2293261, "delivery_pct": 55.85, "sector": "PHARMA"},
            {"name": "HCL Technologies", "ticker": "HCLTECH", "ltp": 1071.80, "change": -30.60, "change_pct": -2.78, "volume": 5186504, "delivery_qty": 2835641, "delivery_pct": 54.67, "sector": "IT"},
            {"name": "TCS", "ticker": "TCS", "ltp": 2031.50, "change": -66.40, "change_pct": -3.17, "volume": 3412470, "delivery_qty": 1862431, "delivery_pct": 54.58, "sector": "IT"},
            {"name": "Jio Financial", "ticker": "JIOFIN", "ltp": 236.44, "change": -0.27, "change_pct": -0.11, "volume": 9229023, "delivery_qty": 4912195, "delivery_pct": 53.23, "sector": "FINANCIALS"},
            {"name": "Tata Motors PV", "ticker": "TATAMOTORS", "ltp": 352.20, "change": 7.15, "change_pct": 2.07, "volume": 11882122, "delivery_qty": 6295583, "delivery_pct": 52.98, "sector": "AUTO"},
            {"name": "Cipla", "ticker": "CIPLA", "ltp": 1465.40, "change": 11.30, "change_pct": 0.78, "volume": 4162869, "delivery_qty": 1995271, "delivery_pct": 47.93, "sector": "PHARMA"},
            {"name": "Tata Consumer", "ticker": "TATACONSUM", "ltp": 1075.60, "change": -37.20, "change_pct": -3.34, "volume": 1632263, "delivery_qty": 769005, "delivery_pct": 47.11, "sector": "FMCG"},
            {"name": "Trent", "ticker": "TRENT", "ltp": 3282.60, "change": 24.30, "change_pct": 0.75, "volume": 2676532, "delivery_qty": 1203445, "delivery_pct": 44.96, "sector": "FMCG"},
            {"name": "Dr Reddy's", "ticker": "DRREDDY", "ltp": 1357.10, "change": -18.60, "change_pct": -1.35, "volume": 8857211, "delivery_qty": 3572002, "delivery_pct": 40.33, "sector": "PHARMA"},
            {"name": "Adani Enterprises", "ticker": "ADANIENT", "ltp": 3036.00, "change": 73.50, "change_pct": 2.48, "volume": 1693354, "delivery_qty": 665110, "delivery_pct": 39.28, "sector": "CONGLOMERATE"},
        ]
        return pd.DataFrame(fallback)


# =============================================================================
# TECHNICAL ANALYSIS ENGINE
# =============================================================================

class TechnicalAnalyzer:
    """Complete technical analysis for swing trading."""

    @staticmethod
    def ema(series, period):
        return series.ewm(span=period, adjust=False).mean()

    @staticmethod
    def sma(series, period):
        return series.rolling(window=period).mean()

    @staticmethod
    def rsi(series, period=14):
        delta = series.diff()
        gain = delta.where(delta > 0, 0).rolling(window=period).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
        rs = gain / loss
        return 100 - (100 / (1 + rs))

    @staticmethod
    def macd(series, fast=12, slow=26, signal=9):
        ema_fast = series.ewm(span=fast, adjust=False).mean()
        ema_slow = series.ewm(span=slow, adjust=False).mean()
        macd_line = ema_fast - ema_slow
        signal_line = macd_line.ewm(span=signal, adjust=False).mean()
        return macd_line, signal_line, macd_line - signal_line

    @staticmethod
    def atr(high, low, close, period=14):
        tr1 = high - low
        tr2 = abs(high - close.shift())
        tr3 = abs(low - close.shift())
        tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
        return tr.rolling(window=period).mean()

    @staticmethod
    def bollinger_bands(series, period=20, std=2):
        mid = series.rolling(window=period).mean()
        std_dev = series.rolling(window=period).std()
        return mid + std * std_dev, mid, mid - std * std_dev

    @staticmethod
    def adx(high, low, close, period=14):
        """Average Directional Index"""
        plus_dm = high.diff()
        minus_dm = -low.diff()
        plus_dm[plus_dm < 0] = 0
        minus_dm[minus_dm < 0] = 0
        # Wilder rule: only larger of +DM/-DM counts per bar, other goes to 0
        mask_plus_wins = plus_dm > minus_dm
        minus_dm[mask_plus_wins] = 0
        plus_dm[~mask_plus_wins] = 0

        tr = pd.concat([high - low, abs(high - close.shift()), abs(low - close.shift())], axis=1).max(axis=1)
        atr = tr.rolling(window=period).mean()

        plus_di = 100 * (plus_dm.rolling(window=period).mean() / atr)
        minus_di = 100 * (minus_dm.rolling(window=period).mean() / atr)
        dx = 100 * abs(plus_di - minus_di) / (plus_di + minus_di)
        adx = dx.rolling(window=period).mean()
        return adx, plus_di, minus_di

    @staticmethod
    def obv(close, volume):
        """On Balance Volume"""
        obv = pd.Series(index=close.index, dtype=float)
        obv.iloc[0] = volume.iloc[0]
        for i in range(1, len(close)):
            if close.iloc[i] > close.iloc[i-1]:
                obv.iloc[i] = obv.iloc[i-1] + volume.iloc[i]
            elif close.iloc[i] < close.iloc[i-1]:
                obv.iloc[i] = obv.iloc[i-1] - volume.iloc[i]
            else:
                obv.iloc[i] = obv.iloc[i-1]
        return obv

    @staticmethod
    def stochastic(high, low, close, k_period=14, d_period=3):
        lowest_low = low.rolling(window=k_period).min()
        highest_high = high.rolling(window=k_period).max()
        k = 100 * (close - lowest_low) / (highest_high - lowest_low)
        d = k.rolling(window=d_period).mean()
        return k, d


# =============================================================================
# SWING TRADE ANALYZER
# =============================================================================

class SwingTradeAnalyzer:
    """Analyzes stocks for swing trade opportunities."""

    def __init__(self, period='3mo', interval='1d'):
        self.period = period
        self.interval = interval
        self.ta = TechnicalAnalyzer()

    def fetch_data(self, ticker):
        """Fetch historical data from Yahoo Finance."""
        try:
            # Add .NS suffix for NSE stocks
            nse_ticker = ticker + '.NS' if not ticker.endswith('.NS') else ticker
            stock = yf.Ticker(nse_ticker)
            df = stock.history(period=self.period, interval=self.interval)
            if df.empty or len(df) < 30:
                return None
            return df
        except Exception as e:
            return None

    def analyze(self, ticker, scanx_data=None):
        """Full technical analysis for a stock."""
        df = self.fetch_data(ticker)
        if df is None:
            return None

        result = {
            'ticker': ticker,
            'name': ticker.replace('.NS', ''),
            'last_price': round(df['Close'].iloc[-1], 2),
            'date': df.index[-1].strftime('%Y-%m-%d'),
        }

        # Add scanx data if available
        if scanx_data is not None:
            result['delivery_pct'] = scanx_data.get('delivery_pct', 0)
            result['delivery_qty'] = scanx_data.get('delivery_qty', 0)
            result['volume_scanx'] = scanx_data.get('volume', 0)
            result['change_pct_today'] = scanx_data.get('change_pct', 0)

        # === CALCULATE ALL INDICATORS ===
        df['EMA_9'] = self.ta.ema(df['Close'], 9)
        df['EMA_21'] = self.ta.ema(df['Close'], 21)
        df['EMA_50'] = self.ta.ema(df['Close'], 50)
        df['SMA_200'] = self.ta.sma(df['Close'], 200)

        df['RSI'] = self.ta.rsi(df['Close'], 14)
        df['MACD'], df['MACD_Signal'], df['MACD_Hist'] = self.ta.macd(df['Close'])
        df['ATR'] = self.ta.atr(df['High'], df['Low'], df['Close'], 14)
        df['BB_Upper'], df['BB_Mid'], df['BB_Lower'] = self.ta.bollinger_bands(df['Close'])
        df['ADX'], df['PLUS_DI'], df['MINUS_DI'] = self.ta.adx(df['High'], df['Low'], df['Close'])
        df['OBV'] = self.ta.obv(df['Close'], df['Volume'])
        df['OBV_EMA'] = self.ta.ema(df['OBV'], 20)
        df['Stoch_K'], df['Stoch_D'] = self.ta.stochastic(df['High'], df['Low'], df['Close'])
        df['Vol_SMA20'] = self.ta.sma(df['Volume'], 20)

        latest = df.iloc[-1]
        prev = df.iloc[-2] if len(df) > 1 else latest

        # === 2-WEEK PERFORMANCE ===
        two_week_ago = df['Close'].iloc[-10] if len(df) >= 10 else df['Close'].iloc[0]
        result['return_2w'] = round(((latest['Close'] - two_week_ago) / two_week_ago) * 100, 2)

        one_month_ago = df['Close'].iloc[-20] if len(df) >= 20 else df['Close'].iloc[0]
        result['return_1m'] = round(((latest['Close'] - one_month_ago) / one_month_ago) * 100, 2)

        # === SWING TRADE SIGNALS ===
        signals = []
        score = 0

        # 1. EMA Alignment (Trend)
        ema_bull = latest['EMA_9'] > latest['EMA_21'] > latest['EMA_50']
        ema_bear = latest['EMA_9'] < latest['EMA_21'] < latest['EMA_50']
        price_above_200 = latest['Close'] > latest['SMA_200']

        result['ema_bull'] = ema_bull
        result['ema_bear'] = ema_bear
        result['above_200sma'] = price_above_200

        if ema_bull and price_above_200:
            score += 3
            signals.append("Strong Uptrend (9>21>50 + above 200 SMA)")
        elif ema_bull:
            score += 2
            signals.append("Bullish EMA Alignment")
        elif ema_bear:
            score -= 2
            signals.append("Bearish EMA Alignment")

        # 2. EMA Crossover (Entry Signal)
        ema_cross_bull = (prev['EMA_9'] <= prev['EMA_21']) and (latest['EMA_9'] > latest['EMA_21'])
        ema_cross_bear = (prev['EMA_9'] >= prev['EMA_21']) and (latest['EMA_9'] < latest['EMA_21'])

        result['ema_cross_bull'] = ema_cross_bull
        result['ema_cross_bear'] = ema_cross_bear

        if ema_cross_bull:
            score += 4
            signals.append("BULLISH EMA CROSSOVER (9/21)")
        elif ema_cross_bear:
            score -= 4
            signals.append("BEARISH EMA CROSSOVER (9/21)")

        # 3. RSI Momentum
        rsi = latest['RSI']
        result['rsi'] = round(rsi, 2)

        if 50 < rsi < 70:
            score += 2
            signals.append(f"RSI Momentum ({round(rsi,1)})")
        elif 40 < rsi <= 50:
            score += 1
            signals.append(f"RSI Building ({round(rsi,1)})")
        elif rsi < 30 and ema_bull:
            score += 2
            signals.append(f"RSI Oversold Bounce ({round(rsi,1)})")
        elif rsi > 75:
            score -= 1
            signals.append(f"RSI Overbought ({round(rsi,1)})")

        # 4. MACD
        macd_bull_cross = (prev['MACD'] <= prev['MACD_Signal']) and (latest['MACD'] > latest['MACD_Signal'])
        macd_bear_cross = (prev['MACD'] >= prev['MACD_Signal']) and (latest['MACD'] < latest['MACD_Signal'])
        macd_above = latest['MACD'] > latest['MACD_Signal']

        result['macd_bull_cross'] = macd_bull_cross
        result['macd_bear_cross'] = macd_bear_cross
        result['macd_above'] = macd_above

        if macd_bull_cross:
            score += 3
            signals.append("MACD Bullish Crossover")
        elif macd_bear_cross:
            score -= 3
            signals.append("MACD Bearish Crossover")
        elif macd_above:
            score += 1
            signals.append("MACD Above Signal")

        # 5. Volume Confirmation
        vol_spike = latest['Volume'] > latest['Vol_SMA20'] * 1.5
        result['volume_spike'] = vol_spike
        result['volume_ratio'] = round(latest['Volume'] / latest['Vol_SMA20'], 2) if latest['Vol_SMA20'] > 0 else 0

        if vol_spike and (ema_cross_bull or macd_bull_cross):
            score += 2
            signals.append("Volume Confirmation Spike")
        elif vol_spike:
            score += 1
            signals.append("Volume Spike")

        # 6. Bollinger Bands
        near_lower = latest['Close'] <= latest['BB_Lower'] * 1.02
        near_upper = latest['Close'] >= latest['BB_Upper'] * 0.98

        result['near_bb_lower'] = near_lower
        result['near_bb_upper'] = near_upper

        if near_lower and macd_above:
            score += 2
            signals.append("Near BB Lower + MACD Bullish")
        elif near_upper and not macd_above:
            score -= 1
            signals.append("Near BB Upper (Resistance)")

        # 7. ADX (Trend Strength)
        adx_val = latest['ADX']
        result['adx'] = round(adx_val, 2)

        if adx_val > 25:
            if latest['PLUS_DI'] > latest['MINUS_DI']:
                score += 1
                signals.append(f"Strong Bullish Trend (ADX {round(adx_val,1)})")
            else:
                score -= 1
                signals.append(f"Strong Bearish Trend (ADX {round(adx_val,1)})")

        # 8. OBV Confirmation
        obv_bull = latest['OBV'] > latest['OBV_EMA']
        result['obv_bull'] = obv_bull

        if obv_bull and ema_bull:
            score += 1
            signals.append("OBV Confirming Uptrend")

        # 9. Stochastic
        stoch_k = latest['Stoch_K']
        stoch_d = latest['Stoch_D']
        result['stoch_k'] = round(stoch_k, 2)
        result['stoch_d'] = round(stoch_d, 2)

        if stoch_k > stoch_d and stoch_k < 80:
            score += 1
            signals.append("Stochastic Bullish")

        # === DELIVERY DATA BOOST ===
        if 'delivery_pct' in result and result['delivery_pct'] > 70:
            score += 1
            signals.append(f"High Delivery {result['delivery_pct']}%")

        # === ATR & RISK MANAGEMENT ===
        atr = latest['ATR']
        result['atr'] = round(atr, 2)
        result['atr_pct'] = round((atr / latest['Close']) * 100, 2)

        if score >= 5:
            result['stop_loss'] = round(latest['Close'] - (2 * atr), 2)
            result['target_1'] = round(latest['Close'] + (2 * atr), 2)
            result['target_2'] = round(latest['Close'] + (3.5 * atr), 2)
            result['risk_reward'] = round((result['target_1'] - latest['Close']) / (latest['Close'] - result['stop_loss']), 2)
        elif score <= -5:
            result['stop_loss'] = round(latest['Close'] + (2 * atr), 2)
            result['target_1'] = round(latest['Close'] - (2 * atr), 2)
            result['target_2'] = round(latest['Close'] - (3.5 * atr), 2)
            result['risk_reward'] = round((latest['Close'] - result['target_1']) / (result['stop_loss'] - latest['Close']), 2)
        else:
            result['stop_loss'] = None
            result['target_1'] = None
            result['target_2'] = None
            result['risk_reward'] = None

        # === FINAL CLASSIFICATION ===
        result['score'] = score
        result['signals'] = signals

        if score >= 7:
            result['rating'] = "STRONG BUY"
        elif score >= 5:
            result['rating'] = "BUY"
        elif score >= 3:
            result['rating'] = "WEAK BUY"
        elif score <= -7:
            result['rating'] = "STRONG SELL"
        elif score <= -5:
            result['rating'] = "SELL"
        elif score <= -3:
            result['rating'] = "WEAK SELL"
        else:
            result['rating'] = "NEUTRAL"

        return result


# =============================================================================
# SECTOR ANALYZER
# =============================================================================

class SectorAnalyzer:
    """Analyzes sector performance over 2 weeks."""

    def __init__(self):
        self.ta = TechnicalAnalyzer()

    def analyze_sector(self, sector_name, tickers):
        """Analyze a sector's 2-week performance."""
        returns = []
        volumes = []

        for ticker in tickers:
            try:
                nse_ticker = ticker + '.NS'
                stock = yf.Ticker(nse_ticker)
                df = stock.history(period='1mo', interval='1d')
                if len(df) >= 10:
                    two_week_return = ((df['Close'].iloc[-1] - df['Close'].iloc[-10]) / df['Close'].iloc[-10]) * 100
                    returns.append(two_week_return)

                    # Volume trend
                    recent_vol = df['Volume'].iloc[-5:].mean()
                    prev_vol = df['Volume'].iloc[-15:-5].mean()
                    vol_change = ((recent_vol - prev_vol) / prev_vol) * 100 if prev_vol > 0 else 0
                    volumes.append(vol_change)
            except:
                continue

        if not returns:
            return None

        return {
            'sector': sector_name,
            'sector_full': SECTOR_NAMES.get(sector_name, sector_name),
            'avg_return_2w': round(np.mean(returns), 2),
            'median_return_2w': round(np.median(returns), 2),
            'best_stock_return': round(max(returns), 2),
            'worst_stock_return': round(min(returns), 2),
            'stocks_count': len(returns),
            'avg_volume_change': round(np.mean(volumes), 2) if volumes else 0,
            'momentum_score': round(np.mean(returns) + (np.mean(volumes) * 0.1), 2),
        }


# =============================================================================
# MAIN ORCHESTRATOR
# =============================================================================

class NSESectorSwingScanner:
    """Main scanner that combines sector analysis + swing trade detection."""

    def __init__(self, args=None):
        self.args = args or self._default_args()
        self.scraper = ScanXScraper()
        self.swing_analyzer = SwingTradeAnalyzer(period='3mo', interval='1d')
        self.sector_analyzer = SectorAnalyzer()
        self.results = []

    def _default_args(self):
        class Args:
            sector = None
            min_score = 3
            top_n = 20
            no_scrape = False
        return Args()

    def run(self):
        """Execute the full scanning pipeline."""
        print("=" * 90)
        print("   KIMI_SWING_PRO - NSE SECTOR & SWING TRADE SCANNER")
        print("   God Mode Edition | Data: scanx.trade + Yahoo Finance")
        print(f"   Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
        print("   Output: C:\\Deal\\Kimi_Swing_Pro\\KIMI_SWING_PRO_YYYYMMDD_HHMMSS.xlsx")
        print("   (Fallback: Documents\\Kimi_Swing_Pro or current folder)")
        print("=" * 90)

        # Step 1: Fetch scanx data
        if self.args.no_scrape:
            print("\n[MODE] Using fallback data (no scraping)")
            scanx_df = self.scraper._fallback_data()
        else:
            scanx_df = self.scraper.fetch()

        if self.scraper.used_fallback:
            print("\n" + "!" * 90)
            print("!!  WARNING: LIVE SCRAPE FAILED — USING HARDCODED FALLBACK DATA")
            print("!!  Prices/delivery% below are FROZEN SNAPSHOT (script build date), NOT live.")
            print("!!  Do NOT trade off these numbers. Fix scraper or re-run when scanx.trade reachable.")
            print("!" * 90 + "\n")

        print(f"\n[SCANX] Loaded {len(scanx_df)} stocks with delivery data")

        # Step 2: Sector Analysis (2-week performance)
        print("\n" + "-" * 90)
        print("STEP 1: SECTOR PERFORMANCE ANALYSIS (Last 2 Weeks)")
        print("-" * 90)

        # Group tickers by sector
        sector_tickers = defaultdict(list)
        for _, row in scanx_df.iterrows():
            sector = row.get('sector', 'UNKNOWN')
            if sector != 'UNKNOWN':
                sector_tickers[sector].append(row['ticker'])

        # Also add known stocks for each sector
        for ticker, sector in STOCK_SECTOR_MAP.items():
            if ticker not in [t for t in sector_tickers[sector]]:
                sector_tickers[sector].append(ticker)

        # Analyze each sector
        sector_results = []
        for sector, tickers in sector_tickers.items():
            if len(tickers) < 2:
                continue
            result = self.sector_analyzer.analyze_sector(sector, tickers)
            if result:
                sector_results.append(result)

        # Sort by momentum score
        sector_results.sort(key=lambda x: x['momentum_score'], reverse=True)

        print(f"\n{'RANK':<6}{'SECTOR':<25}{'2W RETURN':<12}{'VOL CHANGE':<12}{'MOMENTUM':<12}{'STOCKS':<8}")
        print("-" * 90)
        for i, sec in enumerate(sector_results, 1):
            print(f"{i:<6}{sec['sector_full']:<25}{sec['avg_return_2w']:>10.2f}%  {sec['avg_volume_change']:>10.2f}%  {sec['momentum_score']:>10.2f}   {sec['stocks_count']:<8}")

        best_sector = sector_results[0]['sector'] if sector_results else None
        best_sector_name = sector_results[0]['sector_full'] if sector_results else "N/A"

        print(f"\n🏆 BEST PERFORMING SECTOR: {best_sector_name} ({best_sector})")
        print(f"   2-Week Avg Return: {sector_results[0]['avg_return_2w']:.2f}%")
        print(f"   Volume Surge: {sector_results[0]['avg_volume_change']:.2f}%")

        # Step 3: Swing Trade Analysis
        print("\n" + "-" * 90)
        print("STEP 2: SWING TRADE ANALYSIS")
        print("-" * 90)

        # Filter stocks by sector if specified
        if self.args.sector:
            target_sector = self.args.sector.upper()
            scanx_df = scanx_df[scanx_df['sector'] == target_sector]
            print(f"[FILTER] Focusing on sector: {target_sector}")

        # Prioritize best sector stocks
        if best_sector and not self.args.sector:
            scanx_df['sector_priority'] = scanx_df['sector'].apply(
                lambda x: 2 if x == best_sector else (1 if x != 'UNKNOWN' else 0)
            )
            scanx_df = scanx_df.sort_values('sector_priority', ascending=False)

        swing_results = []
        tickers_to_analyze = scanx_df['ticker'].unique()[:self.args.top_n * 2]

        for i, ticker in enumerate(tickers_to_analyze, 1):
            if i > self.args.top_n * 2:
                break

            # Get scanx data for this ticker
            ticker_data = scanx_df[scanx_df['ticker'] == ticker]
            scanx_row = ticker_data.iloc[0].to_dict() if len(ticker_data) > 0 else None

            print(f"[{i}/{len(tickers_to_analyze)}] Analyzing {ticker}...", end=' ')

            result = self.swing_analyzer.analyze(ticker, scanx_row)
            if result:
                # Add sector info
                result['sector'] = scanx_row.get('sector', 'UNKNOWN') if scanx_row else 'UNKNOWN'
                result['sector_full'] = SECTOR_NAMES.get(result['sector'], result['sector'])
                swing_results.append(result)
                print(f"Score: {result['score']} | {result['rating']}")
            else:
                print("NO DATA")

        # Step 4: Results & Export
        print("\n" + "=" * 90)
        print("FINAL RESULTS")
        print("=" * 90)

        # Sort by score
        swing_results.sort(key=lambda x: abs(x['score']), reverse=True)

        # Filter by min score
        strong_signals = [r for r in swing_results if abs(r['score']) >= self.args.min_score]

        # Print top bullish
        bullish = [r for r in strong_signals if r['score'] > 0]
        bearish = [r for r in strong_signals if r['score'] < 0]

        print(f"\n🟢 TOP BULLISH SWING TRADES ({len(bullish)} found, min score: {self.args.min_score})")
        print("-" * 90)

        if bullish:
            for i, r in enumerate(bullish[:self.args.top_n], 1):
                print(f"\n{i}. {r['name']} ({r['sector_full']}) - Score: {r['score']}")
                print(f"   Price: ₹{r['last_price']} | RSI: {r['rsi']} | ADX: {r['adx']}")
                print(f"   2W Return: {r['return_2w']}% | 1M Return: {r['return_1m']}%")
                print(f"   Stop Loss: ₹{r['stop_loss']} | Target 1: ₹{r['target_1']} | Target 2: ₹{r['target_2']}")
                print(f"   R:R = 1:{r['risk_reward']} | ATR: {r['atr_pct']}%")
                print(f"   Signals: {', '.join(r['signals'])}")
        else:
            print("No strong bullish signals found.")

        print(f"\n🔴 TOP BEARISH SWING TRADES ({len(bearish)} found)")
        print("-" * 90)

        if bearish:
            for i, r in enumerate(bearish[:self.args.top_n], 1):
                print(f"\n{i}. {r['name']} ({r['sector_full']}) - Score: {r['score']}")
                print(f"   Price: ₹{r['last_price']} | RSI: {r['rsi']} | ADX: {r['adx']}")
                print(f"   Stop Loss: ₹{r['stop_loss']} | Target 1: ₹{r['target_1']} | Target 2: ₹{r['target_2']}")
                print(f"   Signals: {', '.join(r['signals'])}")
        else:
            print("No strong bearish signals found.")

        # Export
        self._export_results(sector_results, swing_results, bullish, bearish)

        print("\n" + "=" * 90)
        print("KIMI_SWING_PRO - Scan Complete")
        print(f"Output saved to: C:\\Deal\\Kimi_Swing_Pro\\ (or fallback location)")
        print("DISCLAIMER: This tool is for educational purposes only.")
        print("Always do your own research before trading. Past performance ≠ future results.")
        print("=" * 90)

    def _export_results(self, sector_results, swing_results, bullish, bearish):
        """Export results to Excel file at C:\\Deal\\Kimi_Swing_Pro."""

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        current_date = datetime.now().strftime('%Y-%m-%d')
        current_time = datetime.now().strftime('%H:%M:%S')

        # Output directory - try multiple locations
        output_dir = r'C:\\Deal\\Kimi_Swing_Pro'

        # Create directory with fallback logic
        created = False
        try:
            os.makedirs(output_dir, exist_ok=True)
            if os.path.exists(output_dir):
                created = True
        except Exception:
            pass

        if not created:
            # Fallback 1: User Documents
            try:
                output_dir = os.path.join(os.path.expanduser('~'), 'Documents', 'Kimi_Swing_Pro')
                os.makedirs(output_dir, exist_ok=True)
                if os.path.exists(output_dir):
                    created = True
            except Exception:
                pass

        if not created:
            # Fallback 2: Current working directory
            output_dir = os.getcwd()
            created = True

        # Main filename: KIMI_SWING_PRO_YYYYMMDD_HHMMSS.xlsx
        filename = f'KIMI_SWING_PRO_{timestamp}.xlsx'
        filepath = os.path.join(output_dir, filename)

        # Prepare dataframes
        sector_df = pd.DataFrame(sector_results)

        # Enhanced swing trades dataframe with better formatting
        swing_data = []
        for r in swing_results:
            swing_data.append({
                'Date': current_date,
                'Time': current_time,
                'Stock': r['name'],
                'Ticker': r['ticker'],
                'Sector': r['sector_full'],
                'Current_Price': r['last_price'],
                'Rating': r['rating'],
                'Score': r['score'],
                'Signal_Type': 'BULLISH' if r['score'] > 0 else ('BEARISH' if r['score'] < 0 else 'NEUTRAL'),
                'RSI': r['rsi'],
                'ADX': r['adx'],
                'ATR_Value': r['atr'],
                'ATR_Pct': r['atr_pct'],
                'Return_2W_Pct': r['return_2w'],
                'Return_1M_Pct': r['return_1m'],
                'Entry_Price': r['last_price'],
                'Stop_Loss': r.get('stop_loss'),
                'Target_1': r.get('target_1'),
                'Target_2': r.get('target_2'),
                'Risk_Reward': r.get('risk_reward'),
                'Delivery_Pct': r.get('delivery_pct'),
                'Volume_Ratio': r.get('volume_ratio'),
                'EMA_Bullish': r.get('ema_bull', False),
                'EMA_Cross_Bull': r.get('ema_cross_bull', False),
                'MACD_Bull_Cross': r.get('macd_bull_cross', False),
                'MACD_Above_Signal': r.get('macd_above', False),
                'Volume_Spike': r.get('volume_spike', False),
                'Near_BB_Lower': r.get('near_bb_lower', False),
                'OBV_Bullish': r.get('obv_bull', False),
                'Stoch_K': r.get('stoch_k'),
                'Stoch_D': r.get('stoch_d'),
                'Signals': '; '.join(r['signals']),
            })

        swing_df = pd.DataFrame(swing_data)

        # Bullish summary
        bullish_data = []
        for idx, r in enumerate(bullish[:20], 1):
            bullish_data.append({
                'Date': current_date,
                'Time': current_time,
                'Rank': idx,
                'Stock': r['name'],
                'Ticker': r['ticker'],
                'Sector': r['sector_full'],
                'Price': r['last_price'],
                'Score': r['score'],
                'RSI': r['rsi'],
                'Stop_Loss': r.get('stop_loss'),
                'Target_1': r.get('target_1'),
                'Target_2': r.get('target_2'),
                'Risk_Reward': r.get('risk_reward'),
                'Signals': '; '.join(r['signals']),
            })
        bullish_df = pd.DataFrame(bullish_data)

        # Bearish summary
        bearish_data = []
        for idx, r in enumerate(bearish[:20], 1):
            bearish_data.append({
                'Date': current_date,
                'Time': current_time,
                'Rank': idx,
                'Stock': r['name'],
                'Ticker': r['ticker'],
                'Sector': r['sector_full'],
                'Price': r['last_price'],
                'Score': r['score'],
                'RSI': r['rsi'],
                'Stop_Loss': r.get('stop_loss'),
                'Target_1': r.get('target_1'),
                'Target_2': r.get('target_2'),
                'Risk_Reward': r.get('risk_reward'),
                'Signals': '; '.join(r['signals']),
            })
        bearish_df = pd.DataFrame(bearish_data)

        # Scan metadata
        meta_data = {
            'Field': [
                'Scanner_Name', 'Version', 'Scan_Date', 'Scan_Time', 
                'Data_Source', 'DELIVERY_DATA_STATUS', 'Total_Stocks_Analyzed', 'Sectors_Covered',
                'Bullish_Signals', 'Bearish_Signals', 'Neutral_Signals',
                'Best_Sector', 'Min_Score_Threshold', 'Top_N_Limit'
            ],
            'Value': [
                'KIMI_SWING_PRO',
                '1.0 - God Mode',
                current_date,
                current_time,
                'scanx.trade + Yahoo Finance',
                'STALE FALLBACK DATA - DO NOT TRUST DELIVERY%' if self.scraper.used_fallback else 'LIVE (scraped this run)',
                len(swing_results),
                len(sector_results),
                len(bullish),
                len(bearish),
                len(swing_results) - len(bullish) - len(bearish),
                sector_results[0]['sector_full'] if sector_results else 'N/A',
                self.args.min_score,
                self.args.top_n
            ]
        }
        meta_df = pd.DataFrame(meta_data)

        # Write to Excel with formatting
        try:
            with pd.ExcelWriter(filepath, engine='openpyxl') as writer:
                # Sheet 1: Metadata
                meta_df.to_excel(writer, sheet_name='Scan_Info', index=False)

                # Sheet 2: Sector Analysis
                sector_df.to_excel(writer, sheet_name='Sector_Analysis', index=False)

                # Sheet 3: All Swing Trades
                swing_df.to_excel(writer, sheet_name='All_Swing_Trades', index=False)

                # Sheet 4: Bullish Signals
                if not bullish_df.empty:
                    bullish_df.to_excel(writer, sheet_name='BULLISH_Signals', index=False)
                else:
                    pd.DataFrame({'Message': ['No bullish signals found']}).to_excel(writer, sheet_name='BULLISH_Signals', index=False)

                # Sheet 5: Bearish Signals
                if not bearish_df.empty:
                    bearish_df.to_excel(writer, sheet_name='BEARISH_Signals', index=False)
                else:
                    pd.DataFrame({'Message': ['No bearish signals found']}).to_excel(writer, sheet_name='BEARISH_Signals', index=False)

                # Sheet 6: Top Picks (Score >= 5)
                top_picks = swing_df[swing_df['Score'] >= 5] if not swing_df.empty else pd.DataFrame()
                if not top_picks.empty:
                    top_picks.to_excel(writer, sheet_name='TOP_PICKS', index=False)
                else:
                    pd.DataFrame({'Message': ['No top picks found']}).to_excel(writer, sheet_name='TOP_PICKS', index=False)

            print(f"\n{'='*70}")
            print(f"✅ EXCEL EXPORTED SUCCESSFULLY!")
            print(f"{'='*70}")
            print(f"   File: {filepath}")
            print(f"   Sheets: Scan_Info | Sector_Analysis | All_Swing_Trades")
            print(f"           BULLISH_Signals | BEARISH_Signals | TOP_PICKS")
            print(f"{'='*70}")

        except ImportError:
            print("\n[ERROR] openpyxl not installed. Installing...")
            os.system('pip install openpyxl')
            print("[INFO] Please re-run the scanner.")
        except Exception as e:
            print(f"\n[ERROR] Excel export failed: {e}")
            # Fallback to CSV
            csv_path = os.path.join(output_dir, f'KIMI_SWING_PRO_{timestamp}.csv')
            swing_df.to_csv(csv_path, index=False)
            print(f"[FALLBACK] Saved as CSV: {csv_path}")


# =============================================================================
# CLI ENTRY POINT
# =============================================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description='KIMI_SWING_PRO - NSE Sector & Swing Trade Scanner',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
KIMI_SWING_PRO - God Mode Edition
Output: C:\\Deal\\Kimi_Swing_Pro\\KIMI_SWING_PRO_YYYYMMDD_HHMMSS.xlsx

Examples:
  python nse_sector_swing_scanner.py
  python nse_sector_swing_scanner.py --sector IT --min-score 5
  python nse_sector_swing_scanner.py --top-n 15
  python nse_sector_swing_scanner.py --no-scrape
        """
    )
    parser.add_argument('--sector', type=str, default=None,
                        help='Filter by sector (IT, BANKING, AUTO, FMCG, PHARMA, etc.)')
    parser.add_argument('--min-score', type=int, default=3,
                        help='Minimum swing trade score to display (default: 3)')
    parser.add_argument('--top-n', type=int, default=20,
                        help='Number of stocks to analyze (default: 20)')
    parser.add_argument('--no-scrape', action='store_true',
                        help='Use fallback data instead of scraping scanx.trade')

    return parser.parse_args()


def main():
    args = parse_args()
    scanner = NSESectorSwingScanner(args)
    scanner.run()


if __name__ == "__main__":
    main()
